CORE-10087 - Migrate remaining network e2e tests to smoke test suite (#4670)
Deleting tests migrated to e2e-tests repo and migrate two remaining tests into the smoke test suite. I've deleted the tests that were testing p2p connectivity via Kafka, since they were disabled until direct access to Kafka was enabled (which is not in any plans at the moment) and connectivity is already tested via flows now in other tests. 

I've also switched the scripts in `app-simulator` to use 5.1 version, because as they stood they were failing with the following:
```
Release "corda" does not exist. Installing it now.
Error: values don't meet the specifications of the schema(s) in the following chart(s):
corda:
- bootstrap: Additional property preinstallCheck is not allowed
```