NOTICK: Restore ability to run Docker Compose plant locally
The problem was that DBWorker was dying like so:
```
08:17:20.689 [main] INFO  net.corda.processors.db.internal.DBProcessorImpl - DB processor stopping.
08:17:20.699 [main] ERROR net.corda.osgi.framework.OSGiFrameworkMain - Error: Unmatched arguments from index 2: 'passphrase', 'so', 'random'!
java.lang.IllegalArgumentException: Unmatched arguments from index 2: 'passphrase', 'so', 'random'
at net.corda.applications.workers.workercommon.WorkerHelpers$Companion.getParams(WorkerHelpers.kt:37) ~[?:?]
at net.corda.applications.workers.db.DBWorker.startup(DBWorker.kt:43) ~[?:?]
at net.corda.osgi.framework.OSGiFrameworkWrap.startApplication(OSGiFrameworkWrap.kt:529) ~[db-worker.jar:?]
at net.corda.osgi.framework.OSGiFrameworkMain$Companion.main(OSGiFrameworkMain.kt:141) [db-worker.jar:?]
at net.corda.osgi.framework.OSGiFrameworkMain.main(OSGiFrameworkMain.kt) [db-worker.jar:?]
```
which was caused by the fact that spaces are not being handled correctly in `docker-compose.yaml`.

Use of spaces been eliminated (yes - I have tried using quotes without much luck) and the underlying password re-coded.

The change is verified by passing E2E and Smoke tests locally.