CORE-1975: Make use of User creation params
Currently fails with:
```
15:56:12.456 [main] ERROR net.corda.osgi.framework.OSGiFrameworkMain - Error: Permission Manager is null. Getter should be called only after service is UP.!
java.lang.IllegalStateException: Permission Manager is null. Getter should be called only after service is UP.
        at net.corda.permissions.management.PermissionManagementService.getPermissionManager(PermissionManagementService.kt:40) ~[?:?]
        at net.corda.tools.setup.rpc.RPCUserSetup.createUser(RPCUserSetup.kt:80) ~[?:?]
```