CORE-9678 Hibernate errors during crypto worker startup (#3312)
Following error was being observed at crypto worker start up:

ERROR: duplicate key value violates unique constraint "crypto_hsm_category_association_uc" Detail: Key (tenant_id, category, deprecated_at)=(rpc-api, JWT_KEY, 0) already exists. Failed to assign SOFT HSM for rpc-api:JWT_KEY 

This must have been caused due to DB find and persist calls not being transactional when it comes to `HSMStoreImpl.associate`.

* Makes `HSMStoreImpl.associate` DB find and persist calls transactional